# Generated by Django 5.2.4 on 2025-07-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key_id', models.IntegerField()),
                ('tex', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('media_url', models.TextField(blank=True, null=True)),
                ('media_type', models.TextField(blank=True, null=True)),
                ('media_size', models.IntegerField(blank=True, null=True)),
                ('media_name', models.TextField(blank=True, null=True)),
                ('media_duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id_sessao', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'sessao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'crud_user',
                'managed': False,
            },
        ),
    ]
